IAmNotAlone-Hot6ix/Hot6ix

src/main/java/com/hotsix/iAmNotAlone/IAmNotAloneApplication.java
=> test: push Test

src/main/java/com/hotsix/iAmNotAlone/domain/membership/controller/SignUpController.java, src/main/java/com/hotsix/iAmNotAlone/domain/membership/service/SignUpService.java, src/main/java/com/hotsix/iAmNotAlone/global/util/S3UploadService.java
**AS-IS**
- 회원가입시 파일을 List<MultipartFile> 형태로 받음
**TO-BE**
- 회원가입시 파일을 List 형태가 아닌 MultipartFile 타입으로 받도록 변경
=> refactor: 회원가입시 이미지를 MultipartFile로 받도록 변경

src/main/java/com/hotsix/iAmNotAlone/domain/membership/controller/SignUpController.java, src/main/java/com/hotsix/iAmNotAlone/domain/membership/model/form/AddMembershipForm.java, src/main/java/com/hotsix/iAmNotAlone/global/config/CorsConfig.java
**AS-IS**
- addAllowedOrigin()에 프론트 url을 등록했었는데 똑같이 cors 에러가 발생
- CorsFilter 에서 registerCorsConfiguration 패턴이 /api/** 로 되어있었음
- 프론트에서 Json 형태로 birth를 보냈는데 null이 return 되었음
**TO-BE**
- registerCorsConfiguration 패턴을 /** 로 변경하여 모든 url로 변경함
- dto에서 @JsonFormat과 @JsonDeserialize 설정해보았음
=> fix: 프론트에서 api 호출시 cors 에러 발생, cors config 수정

src/main/java/com/hotsix/iAmNotAlone/global/config/CorsConfig.java
**AS-IS**
**TO-BE**
- cors config 수정
=> fix: cors config 수정

src/main/java/com/hotsix/iAmNotAlone/domain/membership/controller/SignUpController.java, src/main/java/com/hotsix/iAmNotAlone/domain/membership/model/form/NicknameVerifyForm.java, src/main/java/com/hotsix/iAmNotAlone/domain/membership/repository/MembershipRepository.java, src/main/java/com/hotsix/iAmNotAlone/domain/membership/service/EmailService.java, src/main/java/com/hotsix/iAmNotAlone/domain/membership/service/SignUpService.java, src/main/java/com/hotsix/iAmNotAlone/global/auth/jwt/filter/JwtAuthorizationFilter.java, src/main/java/com/hotsix/iAmNotAlone/global/exception/business/ErrorCode.java
**AS-IS**
- 이메일 인증 유효시간 3분
**TO-BE**
- 이메일 인증 유효시간 5분으로 늘림
- 회원가입시 닉네임 중복 확인 api 추가
=> feat: 회원가입시 닉네임 중복확인 api 추가

src/main/java/com/hotsix/iAmNotAlone/domain/membership/controller/SignUpController.java, src/main/java/com/hotsix/iAmNotAlone/global/auth/jwt/JwtService.java, src/main/java/com/hotsix/iAmNotAlone/global/auth/jwt/filter/JwtAuthenticationFilter.java, src/main/java/com/hotsix/iAmNotAlone/global/auth/jwt/filter/JwtAuthorizationFilter.java, src/main/java/com/hotsix/iAmNotAlone/global/config/SecurityConfig.java, src/main/java/com/hotsix/iAmNotAlone/global/exception/ErrorResponse.java
**AS-IS**
로그인 성공시
header 로 access token,refresh token 날림 --> body로 access token,refresh token 날림
access token 만료시 서버에서 권한없음 응답 추가
프론트에서는 POST /refresh 요청으로 access token,refresh token 재발급 요청 로직 추가
**TO-BE**
=> refactor: login 관련 리팩토링

src/main/java/com/hotsix/iAmNotAlone/global/auth/jwt/JwtService.java, src/main/java/com/hotsix/iAmNotAlone/global/auth/jwt/filter/JwtAuthenticationFilter.java
**AS-IS**
- jwt 토큰 member id 추가
**TO-BE**
=> feat : jwt 토큰 id 추가

src/main/java/com/hotsix/iAmNotAlone/domain/common/BaseEntity.java, src/main/java/com/hotsix/iAmNotAlone/domain/membership/entity/Membership.java, src/main/java/com/hotsix/iAmNotAlone/domain/membership/model/dto/MemberDto.java, src/main/java/com/hotsix/iAmNotAlone/domain/membership/model/dto/MembershipPostDto.java, src/main/java/com/hotsix/iAmNotAlone/domain/membership/service/MembershipService.java, src/main/java/com/hotsix/iAmNotAlone/domain/post/controller/PostController.java, src/main/java/com/hotsix/iAmNotAlone/domain/post/entity/Post.java, src/main/java/com/hotsix/iAmNotAlone/domain/post/model/dto/PostDetailDto.java, src/main/java/com/hotsix/iAmNotAlone/domain/post/model/form/AddPostForm.java, src/main/java/com/hotsix/iAmNotAlone/domain/post/model/form/ModifyPostForm.java, src/main/java/com/hotsix/iAmNotAlone/domain/post/service/PostDetailService.java, src/main/java/com/hotsix/iAmNotAlone/domain/post/service/PostModifyService.java, src/main/java/com/hotsix/iAmNotAlone/domain/post/service/PostRegisterService.java, src/main/java/com/hotsix/iAmNotAlone/global/exception/business/ErrorCode.java, src/main/resources/application.yml
**AS-IS**
**TO-BE**
- 게시글 수정시 사진업로드는 전체 삭제하고, 다시 업로드 하도록 구현 하였음. (고민을 좀 더 해보고 수정을 할 필요가 있어보임)
=> feat: 게시글 작성, 게시글 수정

src/main/java/com/hotsix/iAmNotAlone/domain/post/model/form/AddPostForm.java, src/main/java/com/hotsix/iAmNotAlone/domain/post/service/PostRegisterService.java
**AS-IS**
**TO-BE**
- 게시글 작성시 이미지가 없을 경우를 판단하는 로직 수정 isEmpty()
=> refactor: 게시글 작성시 이미지가 없을 경우를 판단하는 로직 수정

src/main/java/com/hotsix/iAmNotAlone/domain/membership/controller/MembershipController.java, src/main/java/com/hotsix/iAmNotAlone/domain/membership/service/MembershipService.java, src/main/java/com/hotsix/iAmNotAlone/domain/post/controller/PostController.java, src/main/java/com/hotsix/iAmNotAlone/domain/post/service/PostModifyService.java, src/main/java/com/hotsix/iAmNotAlone/domain/post/service/PostRemoveService.java, src/main/java/com/hotsix/iAmNotAlone/global/util/S3UploadService.java
**AS-IS**
**TO-BE**
- 게시글 삭제 기능 구현
-
=> feat: 게시글 삭제 기능 구현

src/main/java/com/hotsix/iAmNotAlone/domain/post/service/PostModifyService.java
**AS-IS**
**TO-BE**
- 게시글 수정시 이미지 업로드 로직 수정
=> refactor: 게시글 수정시 이미지 업로드 로직 수정

build.gradle, src/main/java/com/hotsix/iAmNotAlone/domain/membership/controller/MembershipController.java, src/main/java/com/hotsix/iAmNotAlone/domain/membership/entity/Membership.java, src/main/java/com/hotsix/iAmNotAlone/domain/membership/model/dto/MyMemberDto.java, src/main/java/com/hotsix/iAmNotAlone/domain/membership/repository/MembershipQueryRepository.java, src/main/java/com/hotsix/iAmNotAlone/domain/membership/service/MembershipService.java, src/main/java/com/hotsix/iAmNotAlone/domain/post/controller/PostController.java, src/main/java/com/hotsix/iAmNotAlone/domain/post/model/dto/PostResponseDto.java, src/main/java/com/hotsix/iAmNotAlone/domain/post/repository/PostRepository.java, src/main/java/com/hotsix/iAmNotAlone/domain/post/service/PostPageService.java, src/main/java/com/hotsix/iAmNotAlone/domain/post/service/PostRemoveService.java, src/main/java/com/hotsix/iAmNotAlone/global/util/S3UploadService.java, src/main/resources/application.yml
**AS-IS**
- 마이페이지 회원정보 api 기능 추가
- 마이페이지 게시글 기본 세팅 api 추가
- 마이페이지 무한스크롤 api 추가
**TO-BE**
=> feat: mypage api 추가

src/main/java/com/hotsix/iAmNotAlone/domain/likes/controller/LikesController.java, src/main/java/com/hotsix/iAmNotAlone/domain/likes/repository/LikesRepository.java, src/main/java/com/hotsix/iAmNotAlone/domain/likes/service/LikesRegisterRemoveService.java, src/main/java/com/hotsix/iAmNotAlone/domain/membership/entity/Membership.java, src/main/java/com/hotsix/iAmNotAlone/domain/post/entity/Post.java, src/main/java/com/hotsix/iAmNotAlone/domain/post/repository/PostRepository.java, src/main/java/com/hotsix/iAmNotAlone/global/util/ListToStringConverter.java, src/test/java/com/hotsix/iAmNotAlone/domain/likes/service/LikesRegisterRemoveServiceTest.java
**AS-IS**
- ListToStringConverter 클래스
- return Arrays.asList(test) 고정적 List
**TO-BE**
- Membership 엔티티, Post 엔티티 수정
- likes 관련 업데이트 메서드 추가
- ListToStringConverter 클래스 수정
- Membership.likelist 는 가변적이여야함
- return Arrays.asList(test)는 가변 List가 아니라서 가변 List로 변경
- 테스트 코드는 주석처리함
=> feat: 좋아요 기능 개발

src/main/java/com/hotsix/iAmNotAlone/domain/main/model/dto/PostProjection.java, src/main/java/com/hotsix/iAmNotAlone/domain/main/model/dto/PostProjectionMainDto.java, src/main/java/com/hotsix/iAmNotAlone/domain/main/service/MainService.java
**AS-IS**
- 메인페이지
- MainService null 처리 안되어있음
**TO-BE**
- 메인페이지 보완2
- MainService @Slf4j 어노테이션 추가
- 작성자가 없을 경우 null 처리 추가
=> Refactor: 메인페이지 보완2

src/main/java/com/hotsix/iAmNotAlone/IAmNotAloneApplication.java
**AS-IS**
**TO-BE**
- jenkins 로 CICD 적용
=> ci: CICD Test

src/main/java/com/hotsix/iAmNotAlone/domain/post/model/dto/PostResponseDto.java
**AS-IS**
- Refactor : 게시글 무한스크롤 api post_Img 카멜케이스로 수정
**TO-BE**
=> Refactor/postresponsedto 

src/main/resources/application.yml
**AS-IS**
**TO-BE**
- yml파일 수정
=> docs: yml파일 수정

src/main/java/com/hotsix/iAmNotAlone/domain/membership/controller/MembershipController.java, src/main/java/com/hotsix/iAmNotAlone/domain/membership/model/dto/LikesListPostProjectionDto.java, src/main/java/com/hotsix/iAmNotAlone/domain/membership/model/dto/LikesListPostResponse.java, src/main/java/com/hotsix/iAmNotAlone/domain/membership/model/dto/LikesPostProjection.java, src/main/java/com/hotsix/iAmNotAlone/domain/membership/service/MembershipLikesListService.java, src/main/java/com/hotsix/iAmNotAlone/domain/post/repository/PostRepository.java
=> feat: 관심목록 페이지 기능 구현

src/main/java/com/hotsix/iAmNotAlone/domain/post/model/dto/PostDetailDto.java, src/main/java/com/hotsix/iAmNotAlone/domain/post/service/PostDetailService.java
**AS-IS**
**TO-BE**
- 좋아요 수 가져올때 redis에 저장된 값 더하는 로직 추가
=> refactor: 좋아요 수 가져올때 redis에 저장된 값 더하는 로직 추가

build.gradle, src/main/java/com/hotsix/iAmNotAlone/domain/chat/config/WebSocketConfig.java, src/main/java/com/hotsix/iAmNotAlone/domain/chat/controller/ChatRoomController.java, src/main/java/com/hotsix/iAmNotAlone/domain/chat/domain/ChatRoom.java, src/main/java/com/hotsix/iAmNotAlone/domain/chat/dto/AddChatRoomForm.java, src/main/java/com/hotsix/iAmNotAlone/domain/chat/dto/ChatRoomDto.java, src/main/java/com/hotsix/iAmNotAlone/domain/chat/repository/ChatRoomRepository.java, src/main/java/com/hotsix/iAmNotAlone/domain/chat/service/ChatRoomListService.java, src/main/java/com/hotsix/iAmNotAlone/domain/chat/service/ChatRoomRegisterService.java, src/main/java/com/hotsix/iAmNotAlone/domain/chat/service/ChatRoomRemoveService.java, src/main/java/com/hotsix/iAmNotAlone/domain/membership/model/dto/MembershipSummaryDto.java, src/main/java/com/hotsix/iAmNotAlone/domain/post/model/dto/PostDetailDto.java
**AS-IS**
**TO-BE**
- 채팅방 생성, 조회 기능 추가
=> feat: 채팅방 생성, 조회 기능 추가

src/main/java/com/hotsix/iAmNotAlone/domain/post/model/dto/PostDetailDto.java
**AS-IS**
**TO-BE**
- PostDetailDto에 createdAt 추가
=> feat: PostDetailDto에 createdAt 추가

src/main/java/com/hotsix/iAmNotAlone/domain/comments/controller/CommentController.java, src/main/java/com/hotsix/iAmNotAlone/domain/comments/model/dto/CommentsDetailResponseDto.java, src/main/java/com/hotsix/iAmNotAlone/domain/comments/service/CommentsRegisterService.java, src/main/java/com/hotsix/iAmNotAlone/domain/membership/model/dto/MembershipDetailDto.java
**AS-IS**
게시물 등록할때 dto 값추가,MemberDetailDto 수정
**TO-BE**
=> Refactor : 게시물 등록할때 dto 값추가,MemberDetailDto 수정

src/main/java/com/hotsix/iAmNotAlone/domain/comments/controller/CommentController.java, src/main/java/com/hotsix/iAmNotAlone/domain/comments/model/dto/CommentsUpdateRemoveResponseDto.java, src/main/java/com/hotsix/iAmNotAlone/domain/comments/service/CommentModifyService.java, src/main/java/com/hotsix/iAmNotAlone/domain/comments/service/CommentRemoveService.java
**AS-IS**
게시물 수정 삭제할때 회원아이디값 dto 추가
**TO-BE**
=> Refactor : 게시물 수정 삭제할때 회원아이디값 dto 추가

src/main/java/com/hotsix/iAmNotAlone/domain/main/model/dto/PostMainDto.java, src/main/java/com/hotsix/iAmNotAlone/domain/membership/model/dto/LikesListDto.java
**AS-IS**
- 게시글 조회시 작성한 memberId 값 null 값으로 나오고 있었음
**TO-BE**
- 게시글 조회시 작성한 memberId 값 나오게 수정
=> refactor: 메인화면, 관심목록 화면 수정

src/main/java/com/hotsix/iAmNotAlone/domain/chat/config/WebSocketConfig.java, src/main/java/com/hotsix/iAmNotAlone/domain/chat/controller/ChatMessageController.java, src/main/java/com/hotsix/iAmNotAlone/domain/chat/controller/ChatRoomController.java, src/main/java/com/hotsix/iAmNotAlone/domain/chat/domain/ChatMessage.java, src/main/java/com/hotsix/iAmNotAlone/domain/chat/domain/ChatRoom.java, src/main/java/com/hotsix/iAmNotAlone/domain/chat/dto/AddChatMessageFrom.java, src/main/java/com/hotsix/iAmNotAlone/domain/chat/dto/ChatMessageDto.java, src/main/java/com/hotsix/iAmNotAlone/domain/chat/repository/ChatMessageRepository.java, src/main/java/com/hotsix/iAmNotAlone/domain/chat/repository/ChatRoomRepository.java, src/main/java/com/hotsix/iAmNotAlone/domain/chat/service/ChatMessageService.java, src/main/java/com/hotsix/iAmNotAlone/domain/chat/service/ChatRoomListService.java, src/main/java/com/hotsix/iAmNotAlone/domain/chat/service/ChatRoomRegisterService.java, src/main/java/com/hotsix/iAmNotAlone/domain/post/model/dto/PostDetailDto.java, src/main/java/com/hotsix/iAmNotAlone/global/config/SecurityConfig.java, src/main/java/com/hotsix/iAmNotAlone/global/exception/business/ErrorCode.java
**AS-IS**
**TO-BE**
- 채팅 메세지 기능 추가 - 아직 미완성
=> feat: 채팅 메세지 기능 Test

src/main/java/com/hotsix/iAmNotAlone/domain/chat/config/WebSocketConfig.java
**AS-IS**
**TO-BE**
- WebSocketConfig에 withSockJs 추가
=> feat: WebSocketConfig withSockJs 추가

src/main/java/com/hotsix/iAmNotAlone/domain/chat/config/FilterChannelInterceptor.java, src/main/java/com/hotsix/iAmNotAlone/domain/chat/config/WebSocketConfig.java
**AS-IS**
**TO-BE**
- 간단한 유효성 검사 기능 추가
=> feat: STOMP JWT 토큰 유효성 검사 기능 추가

src/main/java/com/hotsix/iAmNotAlone/domain/chat/domain/ChatMessage.java, src/main/java/com/hotsix/iAmNotAlone/domain/chat/domain/ChatRoom.java, src/main/java/com/hotsix/iAmNotAlone/domain/chat/dto/AddChatMessageFrom.java, src/main/java/com/hotsix/iAmNotAlone/domain/chat/dto/ChatMessageDto.java, src/main/java/com/hotsix/iAmNotAlone/domain/chat/dto/ChatRoomDto.java, src/main/java/com/hotsix/iAmNotAlone/domain/chat/repository/ChatMessageRepository.java, src/main/java/com/hotsix/iAmNotAlone/domain/chat/service/ChatMessageService.java, src/main/java/com/hotsix/iAmNotAlone/domain/chat/service/ChatRoomListService.java, src/main/java/com/hotsix/iAmNotAlone/domain/membership/model/dto/MembershipSummaryDto.java, src/main/java/com/hotsix/iAmNotAlone/global/auth/jwt/filter/JwtAuthorizationFilter.java
**AS-IS**
**TO-BE**
- 채팅리스트에 마지막 메세지와 시간 포함
=> feat: 채팅리스트에 마지막 메세지와 시간 포함

src/main/java/com/hotsix/iAmNotAlone/domain/chat/repository/ChatMessageRepository.java, src/main/java/com/hotsix/iAmNotAlone/domain/chat/service/ChatMessageService.java, src/main/java/com/hotsix/iAmNotAlone/domain/chat/service/ChatRoomListService.java
**AS-IS**
**TO-BE**
- 채팅 메세지 리스트 정렬 순서 변경
=> 채팅 메세지 리스트 정렬 순서 변경

src/main/java/com/hotsix/iAmNotAlone/domain/post/model/dto/PostResponseDto.java
**AS-IS**
PostResponseDto 필드명 변경 likeYn -> like
**TO-BE**
=> Refactor : PostResponseDto 필드명 변경 likeYn -> like

src/main/java/com/hotsix/iAmNotAlone/domain/chat/config/FilterChannelInterceptor.java
feat: STOMP JWT 토큰 유효성 검사 코드 수정
**AS-IS**
- if문 CONNECT 만 되어있음
**TO-BE**
- STOMP JWT 토큰 유효성 검사 코드 수정
- SEND 추가
=> feat: STOMP JWT 토큰 유효성 검사 코드 수정

src/main/java/com/hotsix/iAmNotAlone/global/auth/jwt/filter/JwtAuthenticationFilter.java, src/main/java/com/hotsix/iAmNotAlone/global/config/SecurityConfig.java
**AS-IS**
Refactor : 시큐리티 컨피그 수정
**TO-BE**
=> Refactor : 시큐리티 컨피그 수정

src/main/java/com/hotsix/iAmNotAlone/domain/post/model/dto/PostDetailDto.java, src/main/java/com/hotsix/iAmNotAlone/domain/post/service/PostDetailService.java
**AS-IS**
**TO-BE**
- 게시글 상세페이지 조회 데이터에 댓글 수 추가
=> refactor: 게시글 상세페이지 조회 데이터에 댓글 수 추가

src/main/java/com/hotsix/iAmNotAlone/domain/chat/repository/ChatMessageRepository.java, src/main/java/com/hotsix/iAmNotAlone/domain/chat/service/ChatRoomListService.java
**AS-IS**
- 채팅방 리스트에서 첫 번째 메세지를 가져옴
**TO-BE**
- 채팅방 리스트에서 마지막 메세지를 가져오도록 수정
=> refactor: 채팅방 리스트에서 마지막 채팅기록 가져오도록 수정

src/main/java/com/hotsix/iAmNotAlone/domain/post/model/dto/PostResponseDto.java, src/main/java/com/hotsix/iAmNotAlone/domain/post/service/PostPageService.java
**AS-IS**
Refactor : PostResponseDto 빌더패턴으로 수정,좋아요 로직 수정
**TO-BE**
=> Refactor : PostResponseDto 빌더패턴으로 수정,좋아요 로직 수정

src/main/java/com/hotsix/iAmNotAlone/domain/post/model/dto/PostResponseDto.java
**AS-IS**
Refactor : PostResponseDto 에서 게시물 작성시 고른 address 반환
**TO-BE**
=> Refactor : PostResponseDto 에서 게시물 작성시 고른 address 반환

src/main/java/com/hotsix/iAmNotAlone/domain/chat/config/FilterChannelInterceptor.java, src/main/java/com/hotsix/iAmNotAlone/domain/chat/config/WebSocketConfig.java
**AS-IS**
- 인터셉터
- preSend() 메서드만 구현되어 있음
- 엔드포인트
- HeartbeatTime 설정 안되어 있음
**TO-BE**
- 인터셉터
- postSend() 메서드 추가
- 엔드포인트
- HeartbeatTime 설정 (10초)
=> Refactor: 인터셉터, 엔드포인트 수정

src/main/java/com/hotsix/iAmNotAlone/domain/post/model/dto/PostResponseDto.java, src/main/java/com/hotsix/iAmNotAlone/domain/post/service/PostPageService.java
**AS-IS**
- responseDTO
- 게시글 내용에 '더보기' 붙여서 구현되어 있음
- PostPageService
- 주석처리 된 코드
**TO-BE**
- responseDTO
- 게시글 내용에 '더보기' 삭제
- PostPageService
- 주석처리 된 코드 삭제
=> Refactor: responseDTO 수정, PostPageService 수정

src/main/resources/application.yml
**AS-IS**
**TO-BE**
Refactor : secret key, redirect-uri 환경변수 추가
=> Refactor : secret key, redirect-uri 환경변수 추가

src/main/resources/application.yml
**AS-IS**
Refactor : redirect-uri 주소 변경
**TO-BE**
=> Refactor : redirect-uri 주소 변경

src/main/java/com/hotsix/iAmNotAlone/domain/membership/controller/SignUpController.java, src/main/java/com/hotsix/iAmNotAlone/domain/region/entity/Region.java, src/main/java/com/hotsix/iAmNotAlone/global/auth/jwt/JwtService.java, src/main/java/com/hotsix/iAmNotAlone/global/auth/oauth/PrincipalOauth2UserService.java, src/main/java/com/hotsix/iAmNotAlone/global/config/SecurityConfig.java
**AS-IS**
**TO-BE**
Refactor : oauth 리팩토링
=> Refactor : oauth 리팩토링

src/main/resources/application.yml
Refactor : oauth front test
**AS-IS**
**TO-BE**
=> Refactor : oauth front test

src/main/java/com/hotsix/iAmNotAlone/global/auth/oauth/PrincipalOauth2UserService.java
**AS-IS**
**TO-BE**
- oauth2 url 부분 빌드에러 발생해서 수정
=> refactor: oauth2 이미지 url 수정

src/main/resources/application.yml
**AS-IS**
- 파일 업로드 디폴트 값은 1MB
**TO-BE**
- 파일업로드 최대 용량 10MB로 수정
=> refactor: 파일업로드 최대 용량 10MB로 수정

src/main/java/com/hotsix/iAmNotAlone/domain/membership/controller/SignUpController.java, src/main/java/com/hotsix/iAmNotAlone/global/auth/jwt/JwtService.java, src/main/java/com/hotsix/iAmNotAlone/global/auth/oauth/PrincipalOauth2UserService.java, src/main/java/com/hotsix/iAmNotAlone/global/auth/oauth/dto/TokenResponseDTO.java
feat : 로그아웃 기능 추가
**AS-IS**
**TO-BE**
=> feat : 로그아웃 기능 추가

src/main/java/com/hotsix/iAmNotAlone/domain/likes/repository/LikesRepository.java, src/main/java/com/hotsix/iAmNotAlone/domain/likes/service/LikesRemoveAllService.java, src/main/java/com/hotsix/iAmNotAlone/domain/membership/service/MembershipRemoveService.java, src/main/java/com/hotsix/iAmNotAlone/domain/post/service/PostRemoveService.java
**AS-IS**
- 좋아요 삭제 로직이 없었음
**TO-BE**
- 회원 탈퇴, 게시글 삭제 시 좋아요 삭제
- 좋아요 데이터 삭제
- 좋아요 count decrement
=> Feat: 회원 탈퇴, 게시글 삭제 시 좋아요 삭제

src/main/java/com/hotsix/iAmNotAlone/domain/membership/entity/Membership.java, src/main/java/com/hotsix/iAmNotAlone/domain/membership/model/dto/MembershipDetailDto.java, src/main/java/com/hotsix/iAmNotAlone/domain/membership/model/form/AddMembershipForm.java, src/main/java/com/hotsix/iAmNotAlone/domain/membership/model/form/AddMembershipOAuthForm.java, src/main/java/com/hotsix/iAmNotAlone/domain/membership/model/form/ModifyMembershipForm.java, src/main/java/com/hotsix/iAmNotAlone/domain/membership/repository/MembershipRepository.java, src/main/java/com/hotsix/iAmNotAlone/domain/membership/service/MembershipModifyService.java, src/main/java/com/hotsix/iAmNotAlone/domain/membership/service/MembershipRemoveService.java, src/main/java/com/hotsix/iAmNotAlone/domain/membership/service/OAuthSignUpService.java, src/main/java/com/hotsix/iAmNotAlone/domain/membership/service/SignUpService.java, src/main/java/com/hotsix/iAmNotAlone/domain/personality/controller/PersonalityController.java, src/main/java/com/hotsix/iAmNotAlone/domain/personality/entity/Personality.java, src/main/java/com/hotsix/iAmNotAlone/domain/personality/model/dto/UserPersonalityDto.java, src/main/java/com/hotsix/iAmNotAlone/domain/personality/model/dto/UserRecommendationDto.java, src/main/java/com/hotsix/iAmNotAlone/domain/personality/model/form/PersonalityDto.java, src/main/java/com/hotsix/iAmNotAlone/domain/personality/repository/PersonalityRepository.java, src/main/java/com/hotsix/iAmNotAlone/domain/personality/service/PreferPersonalityGetMembership.java, src/main/java/com/hotsix/iAmNotAlone/domain/personality/type/ActiveTimeType.java, src/main/java/com/hotsix/iAmNotAlone/domain/personality/type/MbtiGoodType.java, src/main/java/com/hotsix/iAmNotAlone/domain/personality/type/PetsType.java, src/main/java/com/hotsix/iAmNotAlone/domain/personality/type/SmokingType.java, src/main/java/com/hotsix/iAmNotAlone/global/exception/business/ErrorCode.java
**AS-IS**
- 성향이 컨버트 기능을 사용해 Membership 안에 들어가 있었음
- 추천기능이 없었음
**TO-BE**
- 일반회원 가입, 수정, 삭제 시 성향 관련 로직 추가
- 소셜회원 가입 시 성향 관련 로직 추가
- 성향기준 회원 추천 기능 개발
- MBTI와 선호 성향의 점수제로 상위권 회원 추천
=> Feat: 성향 관련 기능 변경

src/main/java/com/hotsix/iAmNotAlone/global/auth/oauth/controller/OAuthController.java, src/main/java/com/hotsix/iAmNotAlone/global/auth/oauth/form/OAuth2CodeForm.java
refactor : 카카오 code를 파라미터형식 -> body형식으로 변경
**AS-IS**
**TO-BE**
=> refactor : 카카오 code를 파라미터형식 -> body로 받는 형태

src/main/java/com/hotsix/iAmNotAlone/domain/personality/model/dto/UserPersonalityDto.java, src/main/java/com/hotsix/iAmNotAlone/domain/personality/service/PreferPersonalityGetMembership.java
**AS-IS**
- 조회 시 성향 부분 String으로 반환됨
**TO-BE**
- 조회 시 성향 부분 코드성으로 반환되게 수정
=> Feat: 추천 유저 조회 수정

src/main/java/com/hotsix/iAmNotAlone/domain/personality/service/PreferPersonalityGetMembership.java
**AS-IS**
- Null 예외 처리 안되어있음
**TO-BE**
- Null 예외 처리 추가
=> Feat: 추천 유저 조회 Null 예외처리

src/main/java/com/hotsix/iAmNotAlone/domain/personality/service/PreferPersonalityGetMembership.java
=> Feat: 추천 유저 조회 Null 예외처리2

src/main/java/com/hotsix/iAmNotAlone/domain/personality/service/PreferPersonalityGetMembership.java
**AS-IS**
**TO-BE**
- MBTI 로그 추가
=> Feat: 추천 유저 조회 Null 예외처리3

src/main/java/com/hotsix/iAmNotAlone/domain/membership/repository/MembershipRepository.java, src/main/java/com/hotsix/iAmNotAlone/domain/personality/service/PreferPersonalityGetMembership.java
**AS-IS**
- AndPersonalityIdNotNull 없었음
**TO-BE**
- MembershipRepository 성향 쿼리 메서드 수정
- AndPersonalityIdNotNull 추가
=> Feat: 추천 유저 조회 Null 예외처리 마지막

src/main/java/com/hotsix/iAmNotAlone/domain/personality/model/dto/UserRecommendationDto.java
**AS-IS**
**TO-BE**
- DTO camelcase로 변경
=> Feat: 추천 유저 조회 camelcase 로 변경

src/main/java/com/hotsix/iAmNotAlone/domain/membership/repository/MembershipRepository.java, src/main/java/com/hotsix/iAmNotAlone/domain/personality/service/PreferPersonalityGetMembership.java
**AS-IS**
- 조회 쿼리
-  지역, 성별 기준으로 조회되고 있음
**TO-BE**
- 조회 쿼리 수정
- 지역 제한 없이 성별 기준으로 조회되게 수정
- camelcase 로 수정
=> Feat: 추천 유저 조회 변경

src/main/java/com/hotsix/iAmNotAlone/domain/chat/service/ChatRoomRemoveService.java, src/main/java/com/hotsix/iAmNotAlone/domain/membership/service/MembershipRemoveService.java
**AS-IS**
**TO-BE**
- 회원 탈퇴시 채팅방목록 삭제 로직 추가
- 회원 탈퇴시 카카오 로그인한 경우 이미지 삭제 제외시킴
=> feat: 회원 탈퇴시 채팅방목록 삭제 로직 추가
